import moment from 'moment';

const generateTxtData = (
  isFileNameAutoGenerated: boolean,
  fileName: string
) => {
  const now = moment().format(`ddd - DD/MM/YYYY - HH:mm`);

  if (isFileNameAutoGenerated) {
    return `${now}h\n`;
  } else {
    return `${fileName} - ${now}h\n`;
  }
};
export default generateTxtData;
